version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          RAILS_ENV: test
          BUNDLER_VERSION: 2.0.2
          PGHOST: 127.0.0.1
          PGUSER: izzy
      - image: circleci/mongo:4.0.3
      - image: circleci/redis:latest

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: reinstall bundler 2.0
          command: |
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle
            sudo gem install bundler
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle exec rake db:create db:schema:load db:seed
      - run: bundle exec rubocop rubocop-rails app spec
      - run: bundle exec rspec